on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zondax/circleci@sha256:37f78ab294b35a055768c2305b3f13813e55fb9db4e65f72745ede61dd842c08
    steps:
      - run: git submodule update --init --recursive
      - run: cmake -DCMAKE_BUILD_TYPE=Debug . && make
      # Unfortunately need to disable leak sanitizer https://github.com/google/sanitizers/issues/916
      # Still run all other ASAN components
      - run: GTEST_COLOR=1 ASAN_OPTIONS=detect_leaks=0 ctest -VV

  build_ledger:
    runs-on: ubuntu-latest
    container: zondax/builder-bolos@sha256:5af9542b68b92c12c5c6ae5bd862ff9dbcce063b38755fe9d8153175f6a53338
    env:
      BOLOS_SDK: /home/zondax/project/deps/nanos-secure-sdk
      BOLOS_ENV: /opt/bolos
    steps:
      # Docker entrypoint is not considered
      - run: git submodule update --init --recursive
      - name: Build Standard app
        run: |
            source /home/zondax/.cargo/env
            cd /home/zondax/project
            make